MvcBlogProjesi/Controllers/HomeController.cs
using MvcBlogProjesi.DataModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcBlogProjesi.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
        BlogDbContext dc = new BlogDbContext();
        public ActionResult SonMakaleler()
        {
            //AraKatmandaki(DbContext) Makaleler sınıfından son eklenen 3 makaleyi görüntüleyecek PartialView için modelListe oluşturmalıyız.
            List<Makale> makaleListe = dc.Makales.OrderByDescending(m => m.Tarih).Take(3).ToList();
            return PartialView(makaleListe);
        }
        public ActionResult SonYorumlar()
        {
            //AraKatmandaki(DbContext) Makaleler sınıfından son eklenen 3 makaleyi görüntüleyecek PartialView için modelListe oluşturmalıyız.
            List<Yorum> yorumListe = dc.Yorums.OrderByDescending(y => y.Tarih).Take(3).ToList();
            return PartialView(yorumListe);
        }
        public ActionResult CokKullanilanEtiketler()
        {
            //En çok makaleyle ilişkilendirilen 5 adet etiketi görüntüleyecek PartialView için modelListe oluşturmalıyız.
            List<Etiket> etiketListe = (from e in dc.Etikets
                                        orderby e.Makales.Count descending
                                        select e).Take(5).ToList();
            return PartialView(etiketListe);
        }
        public ActionResult MakalelerByEtiket(int ID)
        {
            var makaleListe = (from e in dc.Etikets
                               where e.EtiketId == ID
                               select e.Makales).ToList();
            return View(makaleListe[0]); //Burada veriler içiçe liste(koleksiyon) halinde geldiği için (ki çoğunlukla sadece 1 tane olacaktır) içerideki ilk listeyi [0] indeksi ile çekip gönderiyoruz.
        }
        public ActionResult MakaleByYorum(int ID)
        {
            Makale yorumMakale = (from y in dc.Yorums
                               where y.YorumId == ID
                               select y.Makale).FirstOrDefault();
            return View(yorumMakale);
        }
    }
}

MvcBlogProjesi/Controllers/MakaleController.cs
using MvcBlogProjesi.DataModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcBlogProjesi.Controllers
{
    public class MakaleController : Controller
    {
        BlogDbContext dc = new BlogDbContext();
        public ActionResult Index()
        {
            List<Makale> makaleListe = dc.Makales.OrderByDescending(m => m.Tarih).ToList();
            return View(makaleListe);
        }
    }
}

MvcBlogProjesi/Controllers/UyelikController.cs
using MvcBlogProjesi.DataModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcBlogProjesi.Controllers
{
    public class UyelikController : Controller
    {
        BlogDbContext dc = new BlogDbContext();
        public ActionResult Index()
        {
            return View();
        }
        public JsonResult UyeListesi()
        {
            var liste = (from u in dc.Uyes
                         select new { uye = u.Ad + " " + u.Soyad, email = u.Email }).ToList();
            return Json(liste, JsonRequestBehavior.AllowGet);
        }
        public ActionResult Register()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Register(RegisterModel model)
        {
            if (!ModelState.IsValid) { return View(); }
            Uye u = new Uye();
            u.Ad = model.Ad;
            u.Soyad = model.Soyad;
            u.Email = model.Email;
            u.Sifre = model.Sifre;
            u.Tarih = DateTime.Now.ToShortDateString();
            dc.Uyes.Add(u);
            dc.SaveChanges();
            return RedirectToAction("UyelikBasarili");
        }
        public ActionResult UyelikBasarili()
        {
            return View();
        }
        public ActionResult UyeGiris()
        {
            return View();
        }
        [HttpPost]
        //[ActionName("UyeGiris")]
        public string UyeGiris(string Email, string Sifre)
        {
            //string email = Request.Form["Email"];
            //string sifre = Request.Form["Sifre"];
            var uye = (from u in dc.Uyes
                       where u.Email == Email && u.Sifre == Sifre
                       select u).FirstOrDefault();
            if (uye == null)
                return "Hatalı email yada şifre girişi!";
            Session["uye"] = uye.UyeId;

            return "Hoşgeldiniz...<script type='text/javascript'>setTimeout(function(){window.location='/'}, 3000);</script>";
        }
    }
}

MvcBlogProjesi/Controllers/YorumController.cs
using MvcBlogProjesi.DataModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcBlogProjesi.Controllers
{
    public class YorumController : Controller
    {
        BlogDbContext dc = new BlogDbContext();
        public ActionResult Index()
        {
            List<Yorum> yorumListe = (from y in dc.Yorums
                                      orderby y.Tarih descending
                                      select y).ToList();
            return View(yorumListe);
        }
        public ActionResult yorumJson()
        {
            return View();
        }
        public ActionResult GelenYorum(Yorum model)
        {
            return View();
        }
    }
}

MvcBlogProjesi/Views/Home/CokKullanilanEtiketler.cshtml
@model List<MvcBlogProjesi.DataModel.Etiket>

<h3>Çok Kullanılan Etiketler</h3>
@foreach (var item in Model)
{
    <div style="border:1px solid black">
        <ul>
            <li><h5>@Html.ActionLink(item.Icerik, "MakalelerByEtiket", new {id = item.EtiketId })</h5></li>
        </ul>
    </div>
}

MvcBlogProjesi/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<br /><br />
<div style="float:left; width:75%">
    @Html.Action("SonMakaleler", "Home")
</div>
<div style="float:left; width:25%">
    @Html.Action("SonYorumlar", "Home")
    @Html.Action("CokKullanilanEtiketler", "Home")
</div>

MvcBlogProjesi/Views/Home/MakaleByYorum.cshtml
@model MvcBlogProjesi.DataModel.Makale

@{
    ViewBag.Title = "MakaleByYorum";
}

<h2>İlgili Makale</h2>

<div style="width:100%; margin-top:25px; box-shadow:0 0 5px gray; padding:25px">
    <h3 style="color:red">@Html.DisplayFor(m => Model.Baslik)</h3>
    <hr />
    @Html.Raw(Model.Icerik)
    <strong>Tarih : @Model.Tarih</strong><hr />
    <h4>Makaleyi Yazan</h4>
    @{ string adsoyad = Model.Uye.Ad + " " + Model.Uye.Soyad;}
    @adsoyad
</div>

MvcBlogProjesi/Views/Home/MakalelerByEtiket.cshtml
@model List<MvcBlogProjesi.DataModel.Makale>

@{
    ViewBag.Title = "MakalelerByEtiket";
}

<h2>İlgili Makaleler</h2>


@foreach (var item in Model)
{
    <div style="width:100%; margin-top:25px; box-shadow:0 0 5px gray; padding:25px">
        <h3 style="color:red">@Html.DisplayFor(m => item.Baslik)</h3>
        <hr />
        @Html.Raw(@item.Icerik)
        <strong>Tarih : @item.Tarih</strong><hr />
        <h4>Makaleyi Yazan</h4>
        @{ string adsoyad = item.Uye.Ad + " " + item.Uye.Soyad;}
        @adsoyad
    </div>
}

MvcBlogProjesi/Views/Home/SonMakaleler.cshtml
@model List<MvcBlogProjesi.DataModel.Makale>

<h3>Son Eklenen Makaleler</h3>
@foreach (var item in Model)
{
    <div style="border:1px solid black">
        <h3>@item.Baslik</h3>
        @*<p>@item.Icerik</p>*@
        @Html.Raw(@item.Icerik)
        <strong>Tarih : @item.Tarih</strong>
    </div>
}

MvcBlogProjesi/Views/Home/SonYorumlar.cshtml
@model List<MvcBlogProjesi.DataModel.Yorum>

<h3>Son Yorumlar</h3>
@foreach (var item in Model)
{
    <div style="border:1px solid black">
        <h4>Üye Bilgileri</h4>
        @{ string adsoyad = item.Uye.Ad + " " + item.Uye.Soyad;}
        @adsoyad
        <h4>Makale Bilgileri</h4>
        @Html.ActionLink(item.Makale.Baslik, "MakaleByYorum", new { id = item.YorumId })
        <h4>Yorum İçeriği </h4>
        @Html.Raw(@item.Icerik)
        <strong>Tarih : @item.Tarih</strong>
    </div>
}

MvcBlogProjesi/Views/Makale/Index.cshtml
@model List<MvcBlogProjesi.DataModel.Makale>

@{
    ViewBag.Title = "Index";
}


<h2>Tüm Makaleler</h2>

@foreach (var item in Model)
{
    <div style="width:100%; margin-top:25px; border:1px solid gray; padding:25px">
        <h3 style="color:red">
            @Html.DisplayFor(m => item.Baslik)
        </h3><hr />
        @Html.Raw(@item.Icerik)<hr />
        @Html.Label("Tarih : ")
        @Html.DisplayFor(m => item.Tarih)<hr />
        <h4>Makaleyi Yazan</h4>
        @{ string adsoyad = item.Uye.Ad + " " + item.Uye.Soyad;}
        @Html.Label("Adı ve Soyadı : ")&nbsp;&nbsp;&nbsp;@adsoyad
    </div>
            }

MvcBlogProjesi/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("MVC Blog Projesi", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Ana Sayfa", "Index", "Home")</li>
                    <li>@Html.ActionLink("Tüm Makaleler", "Index", "Makale")</li>
                    <li>@Html.ActionLink("Tüm Yorumlar", "Index", "Yorum")</li>
                    <li>@Html.ActionLink("Üye Girişi", "UyeGiris", "Uyelik")</li>
                    <li>@Html.ActionLink("Yeni Üyelik", "Register", "Uyelik")</li>
                    <li>@Html.ActionLink("Üye Listesi", "Index", "Uyelik")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - MS-YAZ08 MVC5 Blog Projesi</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

MvcBlogProjesi/Views/Uyelik/Index.cshtml
@model MvcBlogProjesi.DataModel.Uye

@{
    ViewBag.Title = "Index";
}

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<h2>Üye Listesi</h2>
<script type="text/javascript">
    $(document).ready(function () {
        $('#btnUyeGetir').click(function () {
            $.getJSON("/Uyelik/UyeListesi", function (data) {
                $.each(data, function (i, eleman) {
                    $("#divUyeListesi").append((i + 1) + ".üye :" + eleman.uye + ", email : " + eleman.email + "<br/>");
                });
            });
        });
    });

</script>

<input type="submit" value="Üyeleri Listele" id="btnUyeGetir" />
<div id="divUyeListesi"></div>

MvcBlogProjesi/Views/Uyelik/UyeGiris.cshtml
@{
    ViewBag.Title = "UyeGiris";
}

<script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>

@section scripts{
    <style type="text/css">
        #formGenel {
            box-shadow: 0 0 5px gray;
            padding: 25px;
            height: 500px;
        }

        #divSol, #divSag {
            float: left;
            margin-left: 25px;
        }

        input[type=text] {
            width: 250px;
        }

        input[type=password] {
            width: 250px;
        }

        #btnGiris {
            clear: both;
            display: block;
            margin-left: 130px;
        }

        #divSonuc {
            color: red;
        }
    </style>
}
<h2>Üye Giriş</h2>
@using (Ajax.BeginForm("UyeGiris", "Uyelik", new AjaxOptions { HttpMethod = "Post", UpdateTargetId = "divSonuc" }, new { id = "formGenel" }))
{
    <div id="divSol">
        @Html.Label("Email")<br /><br />
        @Html.Label("Şifre")<br /><br />
    </div>
    <div id="divSag">
        @Html.TextBox("Email")<br /><br />
        @Html.TextBox("Sifre", null, new { type = "Password" })<br /><br />
    </div>
    <input type="submit" value="Üye Giriş" id="btnGiris" />
    <div id="divSonuc"></div>
}

MvcBlogProjesi/Views/Uyelik/UyelikBasarili.cshtml
@{
    ViewBag.Title = "UyelikBasarili";
}

<h2>Üyelik kaydınız başarıyla alınmıştır.</h2>

MvcBlogProjesi/Views/Yorum/Index.cshtml
@model List<MvcBlogProjesi.DataModel.Yorum>

@{
    ViewBag.Title = "Index";
}

<h2>Tüm Yorumlar</h2>

@foreach (var item in Model)
{
    <div style="width:100%; margin-top:25px; border:1px solid gray; padding:25px; text-align:center">
        <h3>Üye Bilgileri</h3>
        @{ string adsoyad = item.Uye.Ad + " " + item.Uye.Soyad;}
        @Html.Label("Adı ve Soyadı : ")&nbsp;&nbsp;&nbsp;@adsoyad
        <h3>Makale Bilgileri</h3>
        @Html.DisplayFor(m => item.Makale.Baslik)
        <h3>Yorumun İçeriği</h3>
        @Html.Raw(@item.Icerik)<hr />
    </div>
            }

MvcBlogProjesi/Views/Yorum/yorumJson.cshtml
@{
    ViewBag.Title = "yorumJson";
}
<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<h2>yorumJson</h2>

<div>@Html.Label("Yorum ID") @Html.TextBox("YorumId")</div>
<div>@Html.Label("Yorum İçerik") @Html.TextBox("Icerik")</div>
<div>@Html.Label("Yorum Tarihi") @Html.TextBox("Tarih")</div>
<div><input id="btnGonder" type="submit" value="Yorumu Json olarak Gönder" /></div>

<script type="text/javascript">
    $('#btnGonder').click(function () {
        var Yorum =
            {
                YorumId: $('#YorumId').val(),
                Icerik: $('#Icerik').val(),
                Tarih: $('#Tarih').val()
            };
        $.ajax({
            url: '/Yorum/GelenYorum',
            type: 'Post',
            data: JSON.stringify(Yorum),
            datatype: 'Json',
            contentType: 'application/json; charset=utf-8'
        });
        return false;
    })
</script>